services:
  db:
    restart: unless-stopped
    image: postgres:18
    env_file:
      - ./env/db.env
    environment:
      - POSTGRES_HOST=db
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    restart: unless-stopped
    image: minio/minio:latest
    env_file:
      - ./env/minio.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  backend:
    restart: unless-stopped
    build: ./backend/
    ports:
      - "8080:8080"
    env_file:
      - ./env/db.env
      - ./env/jwt_secret.env
      - ./env/minio.env
    environment:
      - POSTGRES_HOST=db
      - MINIO_HOST=minio
      - MINIO_PUBLIC_HOST=localhost
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  frontend:
    restart: unless-stopped
    build: ./frontend/
    ports:
      - "3000:3000"
    env_file:
      - ./env/api_url.env
    depends_on:
      - backend

volumes:
  pgdata:
  minio_storage:
