spring.application.name=slackr

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:db}
spring.datasource.username=${POSTGRES_USER:user}
spring.datasource.password=${POSTGRES_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:0i6VM1p6SxZUIgqElfwWUsz4jflKqSUg}
jwt.expiration=604800000

frontend.url=${FRONTEND_URL:http://localhost:3000}

minio.url=http://${MINIO_HOST:localhost}:9000
minio.public-url=${MINIO_PUBLIC_URL:http://localhost:9000}
minio.access-key=${MINIO_ROOT_USER:minioadmin}
minio.secret-key=${MINIO_ROOT_PASSWORD:minioadmin}
minio.bucket-name=images